CREATE TABLE ForumThreads (
    ThreadID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    CreationDate DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE ForumPosts (
    PostID INT PRIMARY KEY AUTO_INCREMENT,
    ThreadID INT NOT NULL,
    UserID INT NOT NULL,
    PostText TEXT NOT NULL,
    PostDate DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ThreadID) REFERENCES ForumThreads(ThreadID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
